services:
  db:
    image: docker.seafile.top/seafileltd/mariadb:10.11
    container_name: seafile-mysql
    volumes:
      - "/opt/mysql-data:/var/lib/mysql"
      - "/opt/seafile_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
      - lower_case_table_names=1
      - MARIADB_AUTO_UPGRADE=1

  redis:
    image: docker.seafile.top/seafileltd/redis:8.0
    container_name: seafile-redis
    ports:
      - 6379:6379

  pro:
    image: docker.seafile.top/seafile-dev/seafile-pro-dev:master
    container_name: seafile-pro-dev
    volumes:
      - /root/data:/data:cached
    environment:
      - IS_PRO_VERSION=true
    ports:
     - 80:80
     - 3000:3000
     - 8000:8000
     - 8001:8001
     - 8080:8080
     - 8082:8082
     - 7070:7070
     - 8084:8084
    depends_on:
      - db
      - redis
