version: '3'
services:
  db:
    image: docker.seafile.top/seafile-dev/mariadb:10.3
    container_name: seafile-mysql
    volumes:
      - "/opt/mysql-data:/var/lib/mysql"
      - "/opt/seafile_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
      - lower_case_table_names=1

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    ports:
      - 11211:11211

  # seafile-office-preview:
  #   image: seafileltd/office-preview:latest
  #   container_name: seafile-office-preview
  #   ports:
  #     - 8089:8089
  #   command: bash start.sh
  #   volumes:
  #     - /root/data/office-preview:/shared:cached

  # uncomment the following to add search feature
  #es:
  #  image: elasticsearch:6.8.20
  #  container_name: seafile-es
  #  volumes:
  #    - "/root/data/es-data:/usr/share/elasticsearch/data"
  #  ports:
  #    - 9200:9200
  #    - 9300:9300
  #
  #  environment:
  #    - discovery.type=single-node
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  pro:
    image: docker.seafile.top/seafile-dev/seafile-pro-dev:9.0

    environment:
      - DOCKER_DEV=1
      - LOCAL_USER_ID=1000
      - IS_PRO_VERSION=1
      - LICENSE_DIR=/data/seaf-license
      - PYTHONPATH=$PYTHONPATH:$CONF_PATH:/usr/lib/python3.8/dist-packages:/usr/lib/python3.8/site-packages:/usr/local/lib/python3.8/dist-packages:/usr/local/lib/python3.8/site-packages:/data/dev/seahub/thirdpart:/data/dev/pyes/pyes:/data/dev/portable-python-libevent/libevent:/data/dev/seafobj:/data/dev/seahub/seahub/:/data/dev/
      - PATH=/data/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - SEAHUB_LOG_DIR=/data/logs

    container_name: seafile-pro-dev
    volumes:
      - /root/data:/data:cached
    ports:
     - 8000:8000
     - 8001:8001
     - 8082:8082
     - 3000:3000
     - 3001:3001
     - 5000:5000
     - 80:80
    depends_on:
      - db
      - memcached
    # - es
